version: '3.8'

services:
  master_server:
    image: postgres:16
    container_name: master_server
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./master_server/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./master_server/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - pg_network

  standby_server:
    image: postgres:16
    container_name: standby_server
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - master_server
    volumes:
      - ./standby_server/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./standby_server/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./standby_server/init.sh:/docker-entrypoint-initdb.d/init_standby.sh
    command: >
      bash /docker-entrypoint-initdb.d/init_standby.sh
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
